### PR TITLE
ISPN-14417 The metrics for misses and retrievals are updated after page reload

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-14417

### CODE REVIEW

**Comment by dpanshug** [comment]
@karesti Let me know if we need to backport to 14

**Comment by dpanshug** [comment]
Reloading the whole detail cache page doesn't look good. 

Here's the running demo  [Screencast from 2022-12-15 18-20-56.webm](https://user-images.githubusercontent.com/97534722/208087683-5434def8-559d-4d40-adbb-25a6c8f4ed06.webm)

Maybe we just load below the tabs section. 
Something like this 


@karesti wdyt?

**Review by karesti — APPROVED** [review]
lets approve this

**Comment by karesti** [comment]
@dpanshug yes, please backport

**Pull request merged**
