### PR TITLE
Added new tests covering x-site replication cases.

### PR DESCRIPTION
**Pull request by andyuk1986**
Closes: #531

### CODE REVIEW

**Comment by andyuk1986** [comment]
Please don't merge yet, as I have forgot to add the pull request related action to work with 2 servers.

**Comment by andyuk1986** [comment]
@karesti ready for the review and merge.

**Review by karesti — APPROVED** [review]
Fantastic work @andyuk1986

**Comment by karesti** [comment]
@andyuk1986 great milestone on testing

**Comment by andyuk1986** [comment]
@karesti thanks a lot Katia :)

**Pull request merged**
