### PR TITLE
fix scroll in filter - patternfly

### PR DESCRIPTION
**Pull request by karesti**
Maybe an issue exists already in patternfly
for now I fixed it in our css

Issue related

patternfly/patternfly-react#4217

### CODE REVIEW

**Comment by karesti** [comment]
@pruivo I did not open a jira for this one, since it's a patternfly bug. I'm going to deal with it with the team tomorrow

**Comment by pruivo** [comment]
it isn't working for me (chrome/firefox). If I tried to filter a tx or secured cache, it just scrolls to the top... except if I do double click really fast xD

**Comment by karesti** [comment]
@pruivo are you accessing to the page via localhost:9000 or localhost:9000/console ?

**Comment by karesti** [comment]
@pruivo https://github.com/patternfly/patternfly-react/issues/4217

It will be fixed at a point :)

**Comment by pruivo** [comment]
> @pruivo are you accessing to the page via localhost:9000 or localhost:9000/console ?

I've just tried both and I didn't see any difference.

**Pull request closed without merging**
