### PR TITLE
ISPN-14961 Cache table

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-14961

### CODE REVIEW

**Comment by dpanshug** [comment]
@dvagnero Some doc review pls
@andyuk1986 Added some unit test, pls check

**Comment by andyuk1986** [comment]
Hey @dpanshug , the test failures shows that the pagination on the page is broken. There are 18 caches, but the pagination is not clickable and it shows 1 - 10 of 10. Regards, Anna.

**Comment by andyuk1986** [comment]
Hey @dpanshug , the pagination is fixed now thanks. But I have found another thing: the filtering by feature doesn't work. If I choose Indexed for example, or any from the available list, it shows No Result screen, eventhough there are indexed caches there. And after that the chosen feature is not possible to remove with cross sign on it, only the general cross (Clear filters) work.

**Review by karesti — CHANGES_REQUESTED** [review]
if tests are failing this way something is wrong so this is blocked...

**Comment by dpanshug** [comment]
> if tests are failing this way something is wrong so this is blocked...

Yes, I've identified some modifications that have caused the test cases to fail. Working on fixing it.

**Comment by dpanshug** [comment]
https://github.com/infinispan/infinispan-console/blob/730915fa807c35c6ee2a8e66d9d9f43cd60472d7/src/app/CacheManagers/CacheTableDisplay.tsx#LL415C22-L415C22

**Review by andyuk1986 — COMMENTED** [review]
I have changed the tests accordingly and sent a PR to Dipanshu's related branch. As soon as it is merged, the tests should be passing. At this stage, all found bugs were fixed.

**Review by andyuk1986 — APPROVED** [review]
Approved from my side.

**Pull request merged**
