### PR TITLE
ISPN-14309 Improve Counters Table Filtering

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-14309
https://marvelapp.com/prototype/8d66729/screen/69367847

1) Filter by counter type and storage
2) Table change to Table Composable 
3) Action item: Set Delta

### CODE REVIEW

**Comment by dpanshug** [comment]
Server config for testing
```
<infinispan
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:infinispan:config:15.0 https://infinispan.org/schemas/infinispan-config-15.0.xsd
                            urn:infinispan:server:15.0 https://infinispan.org/schemas/infinispan-server-15.0.xsd"
      xmlns="urn:infinispan:config:15.0"
      xmlns:server="urn:infinispan:server:15.0">

   <cache-container name="default" statistics="true">
      <transport cluster="${infinispan.cluster.name:cluster}" stack="${infinispan.cluster.stack:tcp}" node-name="${infinispan.node.name:}"/>
      <security>
         <authorization/>
      </security>
      <counters xmlns="urn:infinispan:config:counters:15.0">
         <strong-counter name="sp1" initial-value="5" storage="PERSISTENT"/>
         <strong-counter name="sp2" initial-value="5" storage="PERSISTENT"/>
         <strong-counter name="sp3" initial-value="5" storage="PERSISTENT"/>
         <strong-counter name="sp4" initial-value="5" storage="PERSISTENT"/>
         <strong-counter name="sp5" initial-value="5" storage="PERSISTENT"/>
         <strong-counter name="sv1" initial-value="5" storage="VOLATILE"/>
         <strong-counter name="sv2" initial-value="5" storage="VOLATILE"/>
         <strong-counter name="sv3" initial-value="5" storage="VOLATILE"/>
         <strong-counter name="sv4" initial-value="5" storage="VOLATILE"/>
         <strong-counter name="sv5" initial-value="5" storage="VOLATILE"/>
         <strong-counter name="sv6" initial-value="5" storage="VOLATILE"/>
         <weak-counter name="wp1" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp2" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp3" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp4" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp5" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp6" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wp7" initial-value="5" storage="PERSISTENT" concurrency-level="1"/>
         <weak-counter name="wv1" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv2" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv3" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv4" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv5" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv6" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv7" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
         <weak-counter name="wv8" initial-value="5" storage="VOLATILE" concurrency-level="1"/>
     </counters>
   </cache-container>

   <server xmlns="urn:infinispan:server:15.0">
      <interfaces>
         <interface name="public">
            <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
         </interface>
      </interfaces>

      <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
         <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
         <socket-binding name="memcached" port="11221"/>
      </socket-bindings>

      <security>
         <credential-stores>
            <credential-store name="credentials" path="credentials.pfx">
               <clear-text-credential clear-text="secret"/>
            </credential-store>
         </credential-stores>
         <security-realms>
            <security-realm name="default">
               <properties-realm groups-attribute="Roles">
                  <user-properties path="users.properties"/>
                  <group-properties path="groups.properties"/>
               </properties-realm>
            </security-realm>
         </security-realms>
      </security>

      <endpoints socket-binding="default" security-realm="default" />
   </server>
</infinispan>
```

**Review by karesti — CHANGES_REQUESTED** [review]
we need to split (I think) the jiras. use this jira for the filtering only ( I will test it well tomorrow) and create a jira that explains this issue only.
make the changes (refactoring) in the same jira please

**Comment by dpanshug** [comment]
> we need to split (I think) the jiras. use this jira for the filtering only ( I will test it well tomorrow) and create a jira that explains this issue only. make the changes (refactoring) in the same jira please

I have already done with "Set delta" feature, I am pushing it and rest we can continue with new jira

**Review by karesti — CHANGES_REQUESTED** [review]
@dpanshug change the JIRA please

**Review by karesti — CHANGES_REQUESTED** [review]
do a more focused issue to be reviewed.

this PR should contain the filtering and table refactoring only.
Set value action is another issue.

**Pull request closed without merging**
