### PR TITLE
[14.0] ISPN-12106 Add a refresh button in the cache detail

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-12106

### CODE REVIEW

**Review by karesti — CHANGES_REQUESTED** [review]
same comment as upstream.

Maybe the UX team can help with the best place to put the button and th style

As Kun please

**Comment by dpanshug** [comment]
> backport the changes please

Done :+1:

**Comment by karesti** [comment]
@dpanshug I can't see the changes

**Review by karesti — CHANGES_REQUESTED** [review]
The button is not the one in main

```
<ToolbarItem>
            <Button
              type="button"
              aria-label={t('caches.actions.refresh')}
              variant="link"
              onClick={() => {
                loadCache(cacheName);
              }}
              icon={<RedoIcon />}
              iconPosition="left"
            >
              {t('caches.actions.refresh')}
            </Button>
          </ToolbarItem>
```

**Comment by dpanshug** [comment]
> @dpanshug I can't see the changes

Sorry, updated the PR.

**Review by karesti — APPROVED** [review]

**Pull request merged**
