### PR TITLE
Fixed the tests after ISPN-15045 is introduced.

### PR DESCRIPTION
**Pull request by andyuk1986**

### CODE REVIEW

**Review by karesti — APPROVED** [review]
LGTM but tests are still broken :(

**Comment by andyuk1986** [comment]
@karesti yes, there is a pagination broken in entries' query page, that's why the test is failing. Dipanshu will look into it tomorrow, and if the pagination will be possible to fix quickly maybe he will include it in this PR so that main branch is fixed by this PR.

**Comment by karesti** [comment]
I'll merge this, and keep going in another pr

**Comment by dpanshug** [comment]
Pagination issue resolved in #386

**Pull request merged**
