### PR TITLE
[14.x] ISPN-14449 Fix dev dependencies

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-14449

### CODE REVIEW

**Comment by karesti** [comment]
@andyuk1986 could you please grab a look here?

**Comment by andyuk1986** [comment]
Sure, looking..

**Comment by andyuk1986** [comment]
Looks good to me, lets wait till tests are ran.

**Comment by karesti** [comment]
@andyuk1986 test passed, please merge

**Review by andyuk1986 — APPROVED** [review]

**Pull request merged**
