### PR TITLE
ISPN-14916 Entries tab

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-14916

### CODE REVIEW

**Comment by andyuk1986** [comment]
@dpanshug I have sent a PR to your repo/branch with test fixes.

**Comment by karesti** [comment]
squash the commits and I'll merge plz 🙏🏻

**Comment by andyuk1986** [comment]
@karesti done!

**Review by karesti — CHANGES_REQUESTED** [review]
Several issues

**Comment by karesti** [comment]
Screenshot 2023-07-03 at 18 47 48
tooltips are empty

**Comment by karesti** [comment]
Screenshot 2023-07-03 at 18 44 00

when there is no entry, the message is not ok

**Review by karesti — APPROVED** [review]

**Pull request merged**
