### PR TITLE
ISPN-13962 Refactoring to adapt to PTF4 forms

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-13962

### CODE REVIEW

**Comment by karesti** [comment]
@dipguptaredhat @andyuk1986 @oraNod don't do any change to the wizard until I'm over here please

**Review by oraNod — COMMENTED** [review]
@karesti I pushed a few minor doc suggestions. One thing that really sticks out to me is the fact the console seems to throw an error as soon as you select a capability.

image

From a user's perspective it's somewhat alarming. It's like you think you did something wrong and it takes a second.

I feel like it would be better if this popped up when selecting the "Next" button if there are errors. Otherwise the user shouldn't see this imo.

**Comment by karesti** [comment]
@oraNod before you could not click on next and you did not know what you missed in any feature. We need to make it visible to the users fixes the errors. We can launch the validation on next button if you wish, but the original form did not enable the button. I did not change anything, I just made  the errors disabling the next button visible. Until now you just need to figure out by yourself without any hint on error displayed.

**Comment by karesti** [comment]
We can add a warning error on the top for now. And decide if we change the next button behaviour. But we can't do both (disable next button and not display any error)

**Review by oraNod — APPROVED** [review]

**Comment by karesti** [comment]
@oraNod your commit is gone but not your changes ;)

**Pull request merged**
