### PR TITLE
ISPN-14695 Role list display

### PR DESCRIPTION
**Pull request by dpanshug**
https://issues.redhat.com/browse/ISPN-14695

### CODE REVIEW

**Comment by andyuk1986** [comment]
Hey Dipanshu, 
I have tried the PR on my local, but couldn't find the Access Management Tab on the sidebar, eventhough the page is available via direct link (see the screenshot). 

image

Best regards,
Anna.

**Comment by dpanshug** [comment]
> I have tried the PR on my local, but couldn't find the Access Management Tab on the sidebar, eventhough the page is available via direct link (see the screenshot).

I've kept the sidebar hidden until we have the required APIs available from backend.
https://github.com/infinispan/infinispan-console/blob/98afbe85d80d8dbbb565a419d877b0bc0e635bd3/src/app/routes.tsx#L159

**Comment by karesti** [comment]
@dpanshug since the backend of role management is not ready, go for the UX design small tasks rather than this please

**Comment by karesti** [comment]
Screenshot 2023-07-04 at 09 47 34

Empty tab should not exist

**Comment by karesti** [comment]
Screenshot 2023-07-04 at 09 48 25

We should add descriptions in the server

@tristantarrant is this available ?

**Review by karesti — CHANGES_REQUESTED** [review]
some changes already necessary

**Comment by karesti** [comment]
Depends on 
https://github.com/infinispan/infinispan/pull/11330
https://github.com/infinispan/infinispan/pull/11326

**Pull request closed without merging**
