### PR TITLE
ISPN-11652 Query values

### PR DESCRIPTION
**Pull request by karesti**
https://issues.redhat.com/browse/ISPN-11652

### CODE REVIEW

**Comment by karesti** [comment]
@gustavonalle @anistor I'm unable to make a query work. could you please help me understand this so I add what it needs to help users with this task ?

**Comment by gustavonalle** [comment]
@karesti From the chat logs, it seems your cache is not indexed and hasn't got the storage setting. 
Here's a quick example to make it work:


```bash
# Create an user and start the server
bin/cli.sh user create user -p user
bin/server.sh

# Create a protostream cache
curl -u user:user -H "Content-Type: application/json" -d '{"distributed-cache":{"mode":"SYNC","encoding":{"key":{"media-type":"application/x-protostream"},"value":{"media-type":"application/x-protostream"}}}}' http://127.0.0.1:11222/rest/v2/caches/cache

# Register a protobuf schema
curl -u user:user -X POST -d 'message Entity { required int32 value=1; }' http://127.0.0.1:11222/rest/v2/caches/___protobuf_metadata/message.proto

# Insert data
curl -u user:user -v  -H 'Content-type: application/json' -d '{"_type":"Entity","value":1}' http://127.0.0.1:11222/rest/v2/caches/cache/1

# Query
curl -u user:user -v  "http://127.0.0.1:11222/rest/v2/caches/cache?action=search&query=FROM%20Entity"
```

output should be:
```json
{
  "total_results": 2,
  "hits": [
    {
      "hit": {
        "_type": "Entity",
        "value": 1
      }
    }
  ]
}

```

**Comment by gustavonalle** [comment]
Alternatively, if your cache is configured as indexed, it will also work

**Comment by karesti** [comment]
To test

create a schema

add a json that corresponds to the schema

And test the query

**Comment by karesti** [comment]
@gustavonalle this is mergeble I think

**Comment by karesti** [comment]
I need this in and fix stuff after so I merge

**Pull request merged**
